### ISSUE TITLE
As an elementary school teacher, I need to regulate the content of my students to make sure they do not share inappropriate content.

### ISSUE THREAD

**Issue by andychen482** [Group-4a/sapphire-code-sparks#6]
**Acceptance Criteria**
- [x] Displays information about user reports
- [x] Teacher has the power to mute students from the gallery
- [x] Teacher can view more detail about the reports users
- [x] The page is seamlessly integrated with the existing design scheme

**Tasks**
- [x] Find a good location to place the page
- [x] Create a basic framework for the page
- [x] Incorporate the muting button in development
- [x] Display reported post information
- [x] Make UI seamless with the existing design scheme
- [x] Create a page that provides greater abilities to the teacher to investigate the code if needed
- [x] Connect with backend for realtime reporting

Scanned with SonarCloud and passed all tests.
