### ISSUE TITLE
As a teacher, my students constantly post inappropriate information and I am unable to stop them. I want a way to moderate what the students post in order to ensure it is school appropriate.

### ISSUE THREAD

**Issue by andychen482** [Group-4a/sapphire-code-sparks#8]
**Acceptance Criteria**
- [x] Displays information about user reports
- [x] Teacher has the power to mute students from the gallery
- [x] Teacher can view more detail about the reports users
- [x] The page is seamlessly integrated with the existing design scheme

**Tasks**
- [x] Find a good location to place the page
- [x] Create a basic framework for the page
- [x] Incorporate the muting button in development
- [x] Display reported post information
- [x] Make UI seamless with the existing design scheme
- [x] Create a page that provides greater abilities to the teacher to investigate the code if needed
- [x] Connect with backend for realtime reporting

Scanned with SonarCloud and passed all tests.
