### ISSUE TITLE
As a teacher, I am worried my students will spam posts in the gallery that I won’t be able to keep up with. I want a system that automatically blocks posting after a certain number.

### ISSUE THREAD

**Issue by andychen482** [Group-4a/sapphire-code-sparks#9]
**Acceptance criteria**
- [x] Posts in the gallery are automatically removed after a certain number of reports
- [x] The teacher can change the limit for the amount of reports needed to automatically hide posts

**Tasks**
- [x] Create new backend parameter for each post/student that keeps track of the number of reports
- [x] Create new backend parameter for each classroom that sets the limit for the number of reports for each post to automatically hide it
- [x] Update javascript logic to automatically hide posts over a certain limit

Need to update the backend to keep track of the reports.

**Comment by Cool-Cole** [comment]
I have ran into one issue sending post requests to the backend using the Requests library. I plan on addressing it at office hours tomorrow. Once this hurdle is cleared we will be solid.
